const assert=require('assert'),fs=require('fs'),vm=require('vm');
const aiSource=fs.readFileSync('AppsScript/14_DynamicAI.gs','utf8'),geminiSource=fs.readFileSync('AppsScript/02_GeminiService.gs','utf8');
const context={console,Date,JSON,Object,Array,Number,String,Math,Set,cleanText_:v=>String(v??'').trim(),maskDynamicPersonalInfo_:v=>String(v??''),getDynamicAISetting_:(s,k,f)=>s[f]||'',callGeminiJson_:null};vm.createContext(context);vm.runInContext(aiSource,context);
const opinions=[];for(let i=1;i<=96;i++)opinions.push({responseNumber:String(i),text:i<=10?'없습니다':i<=18?'좋아요':i<=38?'자료 검색 기능을 개선해 주세요':'개별 의견 '+i});context.analysis={text:[{columnNumber:14,question:'의견',opinions}]};context.settings={surveyName:'성능 테스트'};let calls=0,captured='';context.callGeminiJson_=(prompt)=>{calls++;captured=prompt;const match=prompt.match(/\[(14-19)\]/);return {categories:[{categoryName:'검색 개선',sentiment:'SUGGESTION',opinionIds:[match[1]],representativeOpinions:['검색 기능 개선 요구']} ]};};const result=vm.runInContext('analyzeDynamicOpinionsWithAI_(analysis,settings)',context);assert.strictEqual(calls,1);assert.strictEqual(result.validCount,96);assert.strictEqual(result.opinionAssignments.length,96);assert.strictEqual(result.categories.find(c=>c.category==='의견 없음').count,10);assert.strictEqual(result.categories.find(c=>c.category==='긍정 의견 및 감사').count,8);assert.strictEqual(result.categories.find(c=>c.category==='검색 개선').count,20);assert.strictEqual((captured.match(/자료 검색 기능을 개선해 주세요/g)||[]).length,1);assert(captured.includes('동일 의견 수: 20'));
let fetchCalls=0,payloads=[];const gemini={console,Date,JSON,Object,Array,Math,encodeURIComponent,APP_CONFIG:{GEMINI_API_BASE:'https://example.test'},getGeminiApiKey_:()=> 'key',getGeminiModel_:()=> 'model',Utilities:{sleep(){}},UrlFetchApp:{fetch(url,options){payloads.push(JSON.parse(options.payload));fetchCalls++;const reason=fetchCalls===1?'MAX_TOKENS':'STOP';return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({candidates:[{finishReason:reason,content:{parts:[{text:reason==='STOP'?'완결 응답':'부분 응답'}]}}]})};}}};vm.createContext(gemini);vm.runInContext(geminiSource,gemini);gemini.payload={contents:[{parts:[{text:'normal prompt'}]}]};gemini.options={operation:'dynamic-summary',maxAttempts:2,compactPayload:()=>({contents:[{parts:[{text:'compact prompt'}]}]})};assert.strictEqual(vm.runInContext('callGeminiText_(payload,options)',gemini),'완결 응답');assert.strictEqual(fetchCalls,2);assert.strictEqual(payloads[0].contents[0].parts[0].text,'normal prompt');assert.strictEqual(payloads[1].contents[0].parts[0].text,'compact prompt');
const promo=fs.readFileSync('AppsScript/03_PromoService.gs','utf8');assert(promo.includes('callGeminiText_('),'Promotion continues to use the backward-compatible common API');
console.log('Dynamic AI filtering, deduplication, count restoration and compact retry checks passed');
let failedCalls=0;const failed={console,Date,JSON,Object,Array,Math,encodeURIComponent,APP_CONFIG:{GEMINI_API_BASE:'https://example.test'},getGeminiApiKey_:()=> 'key',getGeminiModel_:()=> 'model',Utilities:{sleep(){}},UrlFetchApp:{fetch(){failedCalls++;return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({candidates:[{finishReason:'MAX_TOKENS',content:{parts:[{text:'미완성'}]}}]})};}}};vm.createContext(failed);vm.runInContext(geminiSource,failed);failed.payload={contents:[{parts:[{text:'normal'}]}]};failed.options={operation:'dynamic-future-plan',maxAttempts:2,compactPayload:()=>({contents:[{parts:[{text:'compact'}]}]})};assert.throws(()=>vm.runInContext('callGeminiText_(payload,options)',failed),/완전하게 생성되지 않았습니다/);assert.strictEqual(failedCalls,2);
context.contextAnalysis={respondentCount:96,scaleSummary:{},scoreSummary:null,scale:[],score:[],recommendation:[],multiple:[],respondent:[],single:[]};context.quality={status:'PASS'};context.opinionResult=result;const summaryContext=vm.runInContext('buildDynamicAIContext_(contextAnalysis,opinionResult,settings,quality)',context);assert(!Object.prototype.hasOwnProperty.call(summaryContext.opinionSummary,'opinionAssignments'));assert(!JSON.stringify(summaryContext).includes('개별 의견 39'));assert(aiSource.includes('thinkingConfig:{thinkingBudget:0}')&&aiSource.includes('maxAttempts:2'));
