const assert=require('assert'),fs=require('fs'),vm=require('vm');
const app=fs.readFileSync('Web/survey-dashboard-v2-app.html','utf8');
const script=app.slice(app.indexOf('<script>')+8,app.lastIndexOf('</script>'));
function functionSource(name){const start=script.indexOf(`function ${name}(`);assert(start>=0,`${name} exists`);const brace=script.indexOf('{',start);let depth=0,quote='',escaped=false;for(let i=brace;i<script.length;i++){const c=script[i];if(quote){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c===quote)quote='';continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c==='{')depth++;if(c==='}'&&--depth===0)return script.slice(start,i+1);}throw new Error(`unterminated ${name}`);}
function install(context,names){vm.createContext(context);names.forEach(name=>vm.runInContext(functionSource(name),context));}
(async function(){
  // A. The real renderUpload body executes under strict mode without leaking globals.
  const elements=new Proxy({}, {get:(target,id)=>target[id]||(target[id]={hidden:false,className:'',textContent:'',disabled:false,title:'',innerHTML:'',setAttribute(){}})});
  const renderContext={state:{selectedFile:null,googleFormSource:null,respondentCount:0,mappings:[],filePayload:null,uploadStatus:'idle',error:'',inputSource:'EXCEL'},el:id=>elements[id],Boolean,setButtonBusy_(){},escapeHtml:String};
  install(renderContext,['renderUpload']);vm.runInContext('"use strict";renderUpload()',renderContext);assert.strictEqual(elements.v2GoogleFormManualPanel.hidden,false);

  // B. Saving renders first, calls the secure API, and advances to upload.
  const saveEvents=[];const saveContext={state:{newWorkspaceIntent:false},beginNewWorkspace_:()=>Promise.resolve({}),render(){},Object,collectSettings:()=>({surveyName:'새 조사',surveyPurpose:'목적',surveyPeriod:'2026-01-01 ~ 2026-01-02',surveyTarget:'대상',surveyMethod:'온라인'}),setState:patch=>saveEvents.push(['state',patch.settingsStatus]),showStatus(){},api:{saveSettings:payload=>{saveEvents.push(['api',payload.surveyName]);return Promise.resolve({success:true,settings:payload});}},fillSettingsForm(){},deriveWorkflow(){},navigate:page=>saveEvents.push(['navigate',page]),Date};
  install(saveContext,['saveSettings']);vm.runInContext('saveSettings()',saveContext);await new Promise(resolve=>setImmediate(resolve));assert.deepStrictEqual(saveEvents.slice(0,2),[['state','saving'],['api','새 조사']]);assert.strictEqual(saveContext.state.settingsStatus,'saved');assert.deepStrictEqual(saveEvents.at(-1),['navigate','upload']);

  // C. Switching managed sources clears every previous source-dependent result.
  const oldState={analysisTimer:null,qualityTimer:null,aiTimer:null,respondentCount:44,dashboardData:{old:true},dashboardStatus:'ready',mappings:[1],mappingMeta:{},mappingStatus:'saved',rawDataStatus:'success',analysisStatus:'success',analysisSummary:{old:true},analysisLogs:[1],qualityStatus:'PASS',qualityResult:{old:true},qualityLogs:[1],aiRunStatus:'success',aiResult:{old:true},aiLogs:[1],downloadStatus:'success',downloadResult:{old:true},stale:{analysis:true,quality:true,ai:true,report:true},serverStatus:{mappingExists:true,rawSheetExists:true,statisticsComplete:true,qualityAiAllowed:true,aiComplete:true,exportReady:true},settingsData:{surveyName:'설정 유지'},authenticated:true};
  const sourceStorage={librarySurveyGoogleFormAnalysisSource:'old'};const sourceElements={v2ManagedSurveyPanel:{hidden:false}};const sourceContext={state:oldState,window:{clearInterval(){},location:{href:'https://example.test/exec?page=survey&ui=v2&surveyId=OLD'},history:{replaceState(a,b,url){sourceContext.replaced=url;}}},sessionStorage:{removeItem:key=>delete sourceStorage[key]},GOOGLE_FORM_SOURCE_KEY:'librarySurveyGoogleFormAnalysisSource',URL,Object,Array,Boolean,el:id=>sourceElements[id]||(sourceElements[id]={}),deriveWorkflow(){},render(){},inspectGoogleFormSource_(){}};
  install(sourceContext,['clearSourceContext_','resetSourceDependentState_','connectManagedSurvey_']);sourceContext.survey={surveyId:'SVY-20260826-BBBBBBBB',title:'Form B',responseSpreadsheetId:'sheet-b',formId:'form-b',questions:[]};vm.runInContext('connectManagedSurvey_(survey,false)',sourceContext);
  ['respondentCount','analysisSummary','qualityResult','aiResult','downloadResult','dashboardData','mappingMeta'].forEach(key=>assert(!sourceContext.state[key],`${key} reset`));['mappings','analysisLogs','qualityLogs','aiLogs'].forEach(key=>assert.strictEqual(sourceContext.state[key].length,0,`${key} cleared`));assert.strictEqual(sourceContext.state.rawDataStatus,'idle');assert.strictEqual(sourceContext.state.analysisStatus,'idle');assert.strictEqual(sourceContext.state.downloadStatus,'idle');assert.strictEqual(JSON.stringify(sourceContext.state.stale),JSON.stringify({analysis:false,quality:false,ai:false,report:false}));['mappingExists','rawSheetExists','statisticsComplete','qualityAiAllowed','aiComplete','exportReady'].forEach(key=>assert.strictEqual(sourceContext.state.serverStatus[key],false,`${key} reset`));assert.strictEqual(sourceContext.state.settingsData.surveyName,'설정 유지');assert.strictEqual(sourceContext.state.authenticated,true);assert(sourceContext.replaced.includes('surveyId=SVY-20260826-BBBBBBBB')&&!sourceContext.replaced.includes('spreadsheetId='));

  // D. Workspace context resolves before asynchronous managed-survey restoration.
  const order=[];const initContext={state:{},el:()=>({hidden:false}),restoreState:()=>order.push('restore-state'),hasPendingSourceContext_:()=>true,render:()=>order.push('render'),loadContext:options=>{assert.strictEqual(options.suppressSourceState,true);order.push('load-context');return Promise.resolve().then(()=>order.push('context-ready'));},restoreInputSource_:()=>{order.push('restore-source');return Promise.resolve();}};
  install(initContext,['openApplication']);await vm.runInContext('openApplication()',initContext);assert(order.indexOf('context-ready')<order.indexOf('restore-source'));

  // E. Starting over clears both the stored hint and all source query parameters.
  const resetState=sourceContext.state;sourceContext.state=resetState;sourceContext.UI_STATE_KEY='ui';sourceStorage.ui='old';sourceStorage.librarySurveyGoogleFormAnalysisSource='old';sourceContext.showStatus=()=>{};sourceContext.api={beginWorkspace:()=>Promise.resolve({workspaceId:'ANL-20260826-NEWNEW12'})};sourceContext.Promise=Promise;install(sourceContext,['beginNewWorkspace_','startNewSurvey']);vm.runInContext('startNewSurvey()',sourceContext);assert.strictEqual(sourceStorage.ui,undefined);assert.strictEqual(sourceStorage.librarySurveyGoogleFormAnalysisSource,undefined);assert(!sourceContext.replaced.includes('surveyId=')&&!sourceContext.replaced.includes('source='));assert(app.includes('clearSourceContext_("");window.location.reload()'),'logout clears stale source context');

  // F. OLD WORKSPACE -> NEW SURVEY -> SETTINGS SAVE cannot inherit server or upload state.
  const oldStatus={mappingExists:true,rawSheetExists:true,statisticsComplete:true,qualityStatus:'PASS',qualityAiAllowed:true,aiComplete:true,exportReady:true,respondentCount:82};
  const workspaceStorage={ui:JSON.stringify({currentPage:'upload',uploadStatus:'success'}),hint:'old'};const workspaceState={currentPage:'dashboard',uploadStatus:'idle',selectedFile:null,filePayload:null,inputSource:'EXCEL',googleFormSource:null,settingsData:{surveyName:'이전 조사'},settingsExists:true,lastSavedAt:'',analysisTimer:null,qualityTimer:null,aiTimer:null,serverStatus:oldStatus,respondentCount:82,mappings:[1],analysisSummary:{old:true},qualityResult:{old:true},aiResult:{old:true},downloadResult:{old:true},stale:{analysis:true,quality:true,ai:true,report:true}};
  const workspaceElements={};const workspaceContext={state:workspaceState,STEPS:[{id:'dashboard'},{id:'settings'},{id:'upload'}],UI_STATE_KEY:'ui',GOOGLE_FORM_SOURCE_KEY:'hint',sessionStorage:{getItem:key=>workspaceStorage[key]||null,setItem:(key,value)=>workspaceStorage[key]=value,removeItem:key=>delete workspaceStorage[key]},window:{clearInterval(){},location:{href:'https://example.test/exec?page=survey&ui=v2'},history:{replaceState(){}}},URL,Object,Promise,Date,el:id=>workspaceElements[id]||(workspaceElements[id]={}),render(){},showStatus(){},fillSettingsForm(){},collectSettings:()=>({surveyName:'새 조사',surveyPurpose:'목적',surveyPeriod:'2026-01-01 ~ 2026-01-02',surveyTarget:'대상',surveyMethod:'온라인'}),setState(patch){Object.assign(workspaceState,patch);},deriveWorkflow(){workspaceState.accessibleSteps=['dashboard','settings'];if(workspaceState.settingsExists)workspaceState.accessibleSteps.push('upload');if(workspaceState.serverStatus.mappingExists)workspaceState.accessibleSteps.push('mapping');},navigate:page=>workspaceState.currentPage=page,api:{beginWorkspace:()=>Promise.resolve({workspaceId:'ANL-20260826-ABCDEF12'}),saveSettings:payload=>Promise.resolve({success:true,settings:payload})}};
  install(workspaceContext,['restoreState','clearSourceContext_','resetSourceDependentState_','beginNewWorkspace_','startNewSurvey','saveSettings']);vm.runInContext('restoreState()',workspaceContext);assert.strictEqual(workspaceState.uploadStatus,'idle','upload success is never restored');vm.runInContext('startNewSurvey()',workspaceContext);await workspaceState.workspacePromise;vm.runInContext('saveSettings()',workspaceContext);await new Promise(resolve=>setImmediate(resolve));
  assert.strictEqual(workspaceState.currentPage,'upload');assert.strictEqual(workspaceState.uploadStatus,'idle');assert.strictEqual(workspaceState.respondentCount,0);assert.strictEqual(workspaceState.selectedFile,null);assert.strictEqual(workspaceState.filePayload,null);['mappingExists','rawSheetExists','statisticsComplete','qualityAiAllowed','aiComplete','exportReady'].forEach(key=>assert.strictEqual(workspaceState.serverStatus[key],false,`${key} isolated`));assert(!workspaceState.accessibleSteps.includes('mapping'));assert(workspaceState.lastSavedAt,'settings save timestamp retained');

  // G. Registry count treats an accessible header-only source as zero responses.
  const registry=fs.readFileSync('AppsScript/22_SurveyRegistry.gs','utf8');const countMatch=registry.match(/function managedSurveyResponseCount_\(survey\) \{[\s\S]*?\n\}/);assert(countMatch);const countContext={openGoogleFormResponseSource_:()=>({structure:{responseCount:0}}),console};vm.createContext(countContext);vm.runInContext(countMatch[0],countContext);assert.deepStrictEqual(JSON.parse(JSON.stringify(vm.runInContext('managedSurveyResponseCount_({surveyId:"SVY",questions:[]})',countContext))),{responseCount:0,responseCountAvailable:true});

  // H. Known safe business errors survive friendlyError normalization.
  const errorContext={String};install(errorContext,['friendlyError']);['Google Form 응답 시트에 접근할 수 없습니다.','아직 분석할 설문 응답이 없습니다.','설문을 찾을 수 없습니다.'].forEach(message=>{assert.strictEqual(vm.runInContext(`friendlyError(${JSON.stringify(message)})`,errorContext),message);});
  console.log('survey dashboard v2 runtime smoke checks passed');
})().catch(error=>{console.error(error);process.exit(1);});
