const assert=require('assert'),fs=require('fs'),vm=require('vm');
const reportSource=fs.readFileSync('AppsScript/13_DynamicReport.gs','utf8'),aiSource=fs.readFileSync('AppsScript/14_DynamicAI.gs','utf8'),profileSource=fs.readFileSync('AppsScript/23_SurveyProfiles.gs','utf8');
const scores=[
  ['Q9. 장서구성 평가',84.6667],['Q10. 자료입수 평가 점수',84],['Q11. 자료이용편의 평가 점수',85],
  ['Q12. 사서의 참고서비스 평가 점수',89.6667],['Q13. 온라인 정보제공 평가 점수',82.6667]
].map((entry,index)=>({question:entry[0],average:entry[1],validCount:30,missingCount:0,min:50,max:100,unmappedCount:0,denominator:'유효응답',distribution:[100,90,80,70,60,50].map(score=>({label:score+'점 이하',score,count:index+1}))}));
const scoreSummary={questionCount:5,weightedAverage:85.2,overallAverage:85.2,totalValidResponses:150,highestQuestion:{question:scores[3].question,average:scores[3].average},lowestQuestion:{question:scores[4].question,average:scores[4].average},denominator:'전체 SCORE 유효응답'};
const context={console,Date,JSON,Object,Array,Number,String,Math,Set,Logger:{log(){}},Utilities:{formatDate:()=> '2026-08-30 12:00:00'},Session:{getScriptTimeZone:()=> 'Asia/Seoul'},cleanText_:value=>String(value??'').trim(),normalizeHeader_:value=>String(value||'').toLowerCase().replace(/[\s\p{P}\p{S}]/gu,''),getDynamicSettingValue_:(settings,key,fallback)=>settings[fallback]||'',getDynamicSettingDisplay_:(settings,key,fallback)=>settings[fallback]||'미입력'};
vm.createContext(context);vm.runInContext(profileSource,context);vm.runInContext(reportSource,context);vm.runInContext(aiSource,context);
context.analysis={respondentCount:30,scale:[],scaleSummary:{weightedAverage:null,overallPositiveRate:null},score:scores,scoreSummary,recommendation:[],multiple:[],respondent:[],single:[],text:[]};context.settings={surveyName:'2026년 자료만족도 설문 조사'};
const model=vm.runInContext('buildDynamicDashboardModel_(analysis,settings)',context);assert.strictEqual(model.evaluationMode,'SCORE');assert.strictEqual(model.evaluationSectionTitle,'자료서비스 점수평가 문항별 결과');assert.deepStrictEqual(Array.from(model.kpis.map(item=>item.label)),['총 응답자','자료서비스 종합점수','최고 평가영역','최저 평가영역']);assert.strictEqual(model.kpis[1].displayText,'85.2점');assert(model.kpis[2].displayText.includes('사서 참고서비스')&&model.kpis[2].displayText.includes('89.67점'));assert(model.kpis[3].displayText.includes('온라인 정보제공')&&model.kpis[3].displayText.includes('82.67점'));assert(!JSON.stringify(model.kpis).includes('종합 만족도')&&!JSON.stringify(model).includes('만족도 문항이 없습니다.'));assert(model.interpretations.join(' ').includes('85.2점'));
let writtenRows=null,sectionTitle='';function range(){return {merge(){return this;},setValue(value){if(typeof value==='string'&&(value==='자료서비스 점수평가'||value==='점수 평가'||value==='세부 만족도 분석'))sectionTitle=value;return this;},setValues(value){writtenRows=value;return this;},setBackground(){return this;},setFontColor(){return this;},setFontWeight(){return this;},setFontFamily(){return this;},setFontSize(){return this;},setVerticalAlignment(){return this;},setBorder(){return this;},setNumberFormat(){return this;},setWrap(){return this;},setHorizontalAlignment(){return this;}};}const sheet={getRange(){return range();}};context.sheet=sheet;
vm.runInContext('appendDynamicScoreAnalysis_(sheet,4,analysis)',context);assert.strictEqual(sectionTitle,'자료서비스 점수평가');assert.strictEqual(writtenRows.length,7,'header + SCORE 5 rows + weighted summary');assert.strictEqual(writtenRows[6][0],'전체 가중평균');assert.strictEqual(writtenRows[6][3],85.2);assert(writtenRows[0].includes('100점 이하')&&writtenRows[0].includes('50점 이하'));assert(!writtenRows[0].includes('5점')&&!writtenRows[0].includes('긍정률'));context.genericAnalysis={respondentCount:1,scale:[],scaleSummary:{},score:[Object.assign({},scores[0],{question:'시설 접근성 점수'})],scoreSummary:Object.assign({},scoreSummary,{weightedAverage:77}) ,recommendation:[],multiple:[]};const genericModel=vm.runInContext('buildDynamicDashboardModel_(genericAnalysis,settings)',context);assert.strictEqual(genericModel.evaluationSectionTitle,'점수 평가 문항별 결과');
let calls=[];context.resetDynamicReportSheet_=()=>({getRange(){return range();},setColumnWidth(){},setColumnWidths(){}});context.getDynamicReportSheetName_=()=>'';context.setDynamicReportTitle_=()=>{};context.finishDynamicReportSheet_=()=>{};context.appendDynamicScaleAnalysis_=()=>{calls.push('scale');return 5;};context.appendDynamicScoreAnalysis_=()=>{calls.push('score');return 5;};context.appendDynamicRecommendationAnalysis_=()=>{calls.push('recommendation');return 7;};vm.runInContext('createDynamicSatisfactionSheet_(analysis)',context);assert.deepStrictEqual(calls,['score','recommendation']);calls=[];context.analysis={scale:[{average:4}],score:[],scoreSummary:{},recommendation:[]};vm.runInContext('createDynamicSatisfactionSheet_(analysis)',context);assert.deepStrictEqual(calls,['scale','recommendation']);calls=[];context.analysis={scale:[{average:4}],score:scores,scoreSummary,recommendation:[]};vm.runInContext('createDynamicSatisfactionSheet_(analysis)',context);assert.deepStrictEqual(calls,['scale','score','recommendation']);
context.analysis={respondentCount:30,scale:[],scaleSummary:{},score:scores,scoreSummary,recommendation:[],multiple:[],respondent:[],single:[],text:[]};context.opinions={categories:[],opinionAssignments:[],validCount:0};context.quality={};const ai=vm.runInContext('buildDynamicAIContext_(analysis,opinions,settings,quality)',context);assert.strictEqual(ai.scoreSummary.weightedAverage,85.2);assert.strictEqual(ai.scoreQuestions.length,5);assert.strictEqual(ai.scoreQuestions[3].average,89.6667);
console.log('SCORE dashboard, report layout, distribution and AI context checks passed');
