const assert=require('assert'),fs=require('fs'),vm=require('vm');
const fixture=JSON.parse(fs.readFileSync('tests/fixtures/jungwon-material-satisfaction-2026.json','utf8'));
const normalize=value=>String(value||'').toLowerCase().replace(/[\s\p{P}\p{S}]/gu,'');
let table=[];
function makeRange(row,col){return {setValues(values){values.forEach((valuesRow,r)=>valuesRow.forEach((value,c)=>{const target=row-1+r;while(table.length<=target)table.push([]);table[target][col-1+c]=value;}));return this;},breakApart(){return this;},setFontWeight(){return this;},setBackground(){return this;},setFontColor(){return this;},setHorizontalAlignment(){return this;},setVerticalAlignment(){return this;},setWrap(){return this;}};}
const sheet={clear(){table=[];},getRange(row,col){return makeRange(row,col);},getDataRange(){return Object.assign(makeRange(1,1),{getDisplayValues(){const width=Math.max.apply(null,table.map(row=>row.length));return table.map(row=>Array.from({length:width},(_,index)=>String(row[index]===undefined?'':row[index])));}});},getLastRow(){return table.length;},setFrozenRows(){},autoResizeColumns(){},setColumnWidth(){}};
const spreadsheet={getSheetByName(){return table.length?sheet:null;},insertSheet(){return sheet;}};
const context={console,Date,JSON,Object,Array,Number,String,Math,Set,SpreadsheetApp:{getActiveSpreadsheet:()=>spreadsheet},Utilities:{formatDate:()=> '2026-08-30 12:00:00'},Session:{getScriptTimeZone:()=> 'Asia/Seoul'},DYNAMIC_SURVEY_CONFIG:{SHEETS:{MAPPING:'12_문항매핑',LEGACY_MAPPING:'10_문항매핑'}},cleanText_:value=>String(value??'').trim(),normalizeHeader_:normalize,getSurveyQuestionTypeLabel_:type=>type,round_:(value,digits)=>Number(Number(value).toFixed(digits)),validateSurveyMappings_:()=>({valid:true,errors:[]}),maskDynamicPersonalInfo_:value=>value};
vm.createContext(context);vm.runInContext(fs.readFileSync('AppsScript/23_SurveyProfiles.gs','utf8'),context);vm.runInContext(fs.readFileSync('AppsScript/11_SurveyMapping','utf8'),context);vm.runInContext(fs.readFileSync('AppsScript/12_DynamicAnalysis','utf8'),context);
context.headers=fixture.headers;const detection=vm.runInContext('detectSurveyProfile_(headers)',context);assert.strictEqual(detection.status,'AUTO_PROFILE');assert.strictEqual(detection.matchedQuestionCount,18);assert.deepStrictEqual(Array.from(detection.unmatchedHeaders),['참여자']);
context.base=fixture.headers.map((header,index)=>({columnNumber:index+1,originalHeader:header,suggestedType:index<2?'EXCLUDE':'SINGLE',selectedType:index<2?'EXCLUDE':'SINGLE',analysisTarget:index>=2,scoreMap:{}}));context.detection=detection;context.applied=vm.runInContext('applySurveyProfileMappings_(base,detection)',context);
context.payload={mappings:context.applied,fileName:'naver.xlsx',sheetName:'설문결과',mappingSource:'AUTO_PROFILE'};assert.strictEqual(vm.runInContext('saveSurveyMappingsFromWeb(payload).success',context),true);const loaded=vm.runInContext('getSavedSurveyMappingsFromWeb()',context);assert.strictEqual(loaded.success,true);
assert.deepStrictEqual(Array.from(loaded.mappings.filter(item=>item.displayQuestionNumber>0).map(item=>item.displayQuestionNumber)),Array.from({length:18},(_,index)=>index+1));const scores=loaded.mappings.filter(item=>item.selectedType==='SCORE');assert.strictEqual(scores.length,5);scores.forEach(item=>assert.deepStrictEqual(JSON.parse(JSON.stringify(item.scoreMap)),{'100점 이하':100,'90점 이하':90,'80점 이하':80,'70점 이하':70,'60점 이하':60,'50점 이하':50}));
context.source={headers:fixture.headers,rows:fixture.rows,mappings:loaded.mappings,respondentCount:fixture.rows.length,questionCount:18};const analysis=vm.runInContext('calculateDynamicSurveyAnalysis_(source)',context);assert.strictEqual(analysis.score.length,5);assert.strictEqual(analysis.scoreSummary.totalValidResponses,25);assert.deepStrictEqual(Array.from(analysis.single.map(item=>item.questionId)),['Q1']);assert.deepStrictEqual(Array.from(analysis.multiple.map(item=>item.questionId)),['Q2','Q3','Q4','Q5','Q6','Q7','Q8']);assert.deepStrictEqual(Array.from(analysis.score.map(item=>item.questionId)),['Q9','Q10','Q11','Q12','Q13']);assert.deepStrictEqual(Array.from(analysis.text.map(item=>item.questionId)),['Q14']);assert.deepStrictEqual(Array.from(analysis.respondent.map(item=>item.questionId)),['Q15','Q16','Q17','Q18']);
const q6Community='(커뮤니티) 페이스북, X(舊 트위터), 블로그, 인스타그램, 유튜브, 카카오톡 채널 등',q7Community='(커뮤니티) 페이스북, X(舊 트위터), 인스타그램, 블로그, 유튜브, 카카오톡 채널';const q6=analysis.multiple.find(item=>item.columnNumber===8),q7=analysis.multiple.find(item=>item.columnNumber===9);assert(q6&&q7);assert.strictEqual(q6.items.find(item=>item.label===q6Community).count,2);assert.strictEqual(q7.items.find(item=>item.label===q7Community).count,2);assert(!q6.items.some(item=>item.label==='X(舊 트위터)'||item.label==='블로그'));assert(!q7.items.some(item=>item.label==='X(舊 트위터)'||item.label==='블로그'));
context.generic='A, B, C';assert.deepStrictEqual(Array.from(vm.runInContext('splitDynamicMultipleValue_(generic)',context)),['A','B','C']);
console.log('survey profile real-data accuracy round-trip checks passed');
const dashboardApp=fs.readFileSync('Web/survey-dashboard-v2-app.html','utf8');assert(dashboardApp.includes('multipleChoices:Array.isArray(mapping.multipleChoices)?mapping.multipleChoices:[]'));
